import type { User, Item, Reservation, Pickup, InputHistory, Project } from "./types"

// Mock users for demo
export const mockUsers: User[] = [
  { id: "1", name: "Admin Korisnik", email: "admin@magacin.rs", role: "MAGACIN_ADMIN", userCode: "ADMIN1" },
  { id: "2", name: "Rezervacija Korisnik", email: "rezervacija@magacin.rs", role: "REZERVACIJA", userCode: "REZ001" },
  { id: "3", name: "Preuzimanje Korisnik", email: "preuzimanje@magacin.rs", role: "PREUZIMANJE", userCode: "PRE001" },
  { id: "4", name: "Marko Marković", email: "marko@magacin.rs", role: "REZERVACIJA", userCode: "MARKO1" },
  { id: "5", name: "Ana Anić", email: "ana@magacin.rs", role: "PREUZIMANJE", userCode: "ANA123" },
  { id: "6", name: "Petar Petrović", email: "petar@magacin.rs", role: "REZERVACIJA", userCode: "PETAR1" },
  { id: "7", name: "Jovana Jovanović", email: "jovana@magacin.rs", role: "PREUZIMANJE", userCode: "JOVAN1" },
  { id: "8", name: "Stefan Nastasić", email: "stefan.nastasic@magacin.rs", role: "REZERVACIJA", userCode: "STEFAN1" },
]

export const mockItems: Item[] = [
  {
    id: "1",
    code: "WH-001",
    lokacija: "Polica A1",
    project: "Projekat A",
    name: "Vijci M6x20",
    supplier: "Dobavljač 3",
    price: 0.55,
    input: 1800,
    output: 100,
    stock: 1700,
    reserved: 50,
    available: 1650,
    okov_ime: "Čelik",
    okov_cena: 0.5,
    okov_kom: 800,
    ploce_ime: "Aluminijum",
    ploce_cena: 2.5,
    ploce_kom: 100,
    rezervisao: "Marko Marković",
    vreme_rezervacije: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    sifra_rezervacije: "RES001",
    preuzeo: "Ana Anić",
    vreme_preuzimanja: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    sifra_preuzimanja: "ABC123",
    low_stock_threshold: 100,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    code: "WH-002",
    lokacija: "Polica A2",
    project: "Projekat A",
    name: "Matice M6",
    supplier: "Dobavljač 1",
    price: 0.3,
    input: 800,
    output: 50,
    stock: 750,
    reserved: 0,
    available: 750,
    okov_ime: "Čelik",
    okov_cena: 0.28,
    okov_kom: 400,
    low_stock_threshold: 100,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    code: "WH-003",
    lokacija: "Polica B1",
    project: "Projekat B",
    name: "Šrafovi M8x30",
    supplier: "Dobavljač 2",
    price: 0.75,
    input: 500,
    output: 0,
    stock: 500,
    reserved: 30,
    available: 470,
    okov_ime: "Inox",
    okov_cena: 0.7,
    okov_kom: 250,
    ploce_ime: "Plastika",
    ploce_cena: 1.2,
    ploce_kom: 150,
    rezervisao: "Petar Petrović",
    vreme_rezervacije: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    sifra_rezervacije: "RES002",
    low_stock_threshold: 50,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    code: "WH-004",
    lokacija: "Polica C1",
    project: "Skladište",
    name: "Podloške 8mm",
    supplier: "Dobavljač 2",
    price: 0.2,
    input: 1200,
    output: 0,
    stock: 1200,
    reserved: 0,
    available: 1200,
    okov_ime: "Čelik",
    okov_cena: 0.18,
    okov_kom: 600,
    low_stock_threshold: 150,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    code: "WH-005",
    lokacija: "Polica C2",
    project: "Skladište",
    name: "Kablovi 2.5mm",
    supplier: "Dobavljač 3",
    price: 2.5,
    input: 300,
    output: 0,
    stock: 300,
    reserved: 0,
    available: 300,
    okov_ime: "Bakar",
    okov_cena: 2.3,
    okov_kom: 150,
    ploce_ime: "PVC",
    ploce_cena: 0.2,
    ploce_kom: 150,
    low_stock_threshold: 30,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    code: "WH-006",
    lokacija: "Polica D1",
    project: "Projekat C",
    name: "Prekidači",
    supplier: "Dobavljač 3",
    price: 5.0,
    input: 200,
    output: 0,
    stock: 200,
    reserved: 0,
    available: 8,
    okov_ime: "Plastika",
    okov_cena: 4.5,
    okov_kom: 100,
    ploce_ime: "Metal",
    ploce_cena: 0.5,
    ploce_kom: 100,
    low_stock_threshold: 20,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    code: "WH-007",
    lokacija: "Polica D2",
    project: "Projekat D",
    name: "LED Sijalice",
    supplier: "Dobavljač 4",
    price: 8.0,
    input: 150,
    output: 0,
    stock: 150,
    reserved: 0,
    available: -5,
    okov_ime: "LED",
    okov_cena: 7.5,
    okov_kom: 75,
    ploce_ime: "Aluminijum",
    ploce_cena: 0.5,
    ploce_kom: 75,
    low_stock_threshold: 15,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockReservations: Reservation[] = [
  {
    id: "1",
    item_id: "1",
    quantity: 50,
    reserved_by: "Marko Marković",
    reserved_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    reservation_code: "RES001",
  },
  {
    id: "2",
    item_id: "3",
    quantity: 30,
    reserved_by: "Ana Anić",
    reserved_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    reservation_code: "RES002",
  },
]

export const mockPickups: Pickup[] = [
  {
    id: "1",
    item_id: "1",
    quantity: 100,
    picked_up_by: "Marko Marković",
    picked_up_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    confirmation_code: "ABC123",
    confirmed_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    item_id: "2",
    quantity: 50,
    picked_up_by: "Ana Anić",
    picked_up_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    confirmation_code: "XYZ789",
    confirmed_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockInputHistory: InputHistory[] = [
  {
    id: "1",
    item_id: "1",
    quantity: 1000,
    price: 0.5,
    supplier: "Dobavljač 1",
    input_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    item_id: "2",
    quantity: 800,
    price: 0.3,
    supplier: "Dobavljač 1",
    input_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    item_id: "1",
    quantity: 200,
    price: 0.48,
    supplier: "Dobavljač 2",
    input_date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    item_id: "1",
    quantity: 600,
    price: 0.55,
    supplier: "Dobavljač 3",
    input_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Mock projects with dates
export const mockProjects: Project[] = [
  {
    id: "1",
    name: "Projekat A",
    start_date: "2024-01-15",
    end_date: "2024-03-30",
    color: "#3b82f6",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Projekat B",
    start_date: "2024-02-01",
    end_date: "2024-04-15",
    color: "#10b981",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Projekat C",
    start_date: "2024-03-10",
    end_date: "2024-05-20",
    color: "#f59e0b",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Projekat D",
    start_date: "2024-04-01",
    end_date: "2024-06-30",
    color: "#8b5cf6",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Skladište",
    start_date: "2024-01-01",
    end_date: "2024-12-31",
    color: "#6b7280",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Kuhinja Marković",
    start_date: "2025-11-12",
    end_date: "2025-11-19",
    color: "#ec4899",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
